import { supabase } from '../lib/supabase'
import type { ProductGender, ProductStatus } from '../types/catalog'

export type AdminCategory = { id: string; name: string; gender: ProductGender | null }
export type AdminProduct = { id: string; name: string; slug: string; sku: string; category_id: string; gender: ProductGender; short_description: string; description: string; original_price: number; sale_price: number | null; stock_quantity: number; low_stock_threshold: number; featured: boolean; new_arrival: boolean; best_seller: boolean; status: ProductStatus; product_images: Array<{ storage_path: string; alt_text: string; position: number }> | null }
export type ProductInput = Omit<AdminProduct, 'id' | 'slug' | 'product_images'>

function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }

export async function getAdminCategories() { const { data, error } = await supabase.from('categories').select('id, name, gender').order('name'); if (error) throw error; return (data ?? []) as AdminCategory[] }
export async function createAdminCategory(name: string, gender: ProductGender) { const { data, error } = await supabase.from('categories').insert({ name, gender, slug: slugify(name), active: true }).select('id, name, gender').single(); if (error) throw error; return data as AdminCategory }
export async function getAdminProducts() { const { data, error } = await supabase.from('products').select('id, name, slug, sku, category_id, gender, short_description, description, original_price, sale_price, stock_quantity, low_stock_threshold, featured, new_arrival, best_seller, status, product_images(storage_path, alt_text, position)').order('created_at', { ascending: false }); if (error) throw error; return ((data ?? []) as AdminProduct[]).map((product) => ({ ...product, original_price: Number(product.original_price), sale_price: product.sale_price === null ? null : Number(product.sale_price) })) }
export async function saveAdminProduct(input: ProductInput, id?: string) { const payload = { ...input, slug: slugify(input.name), sale_price: input.sale_price || null }; const response = id ? await supabase.from('products').update(payload).eq('id', id).select('id').single() : await supabase.from('products').insert(payload).select('id').single(); if (response.error) throw response.error; return response.data.id as string }
export async function deleteAdminProduct(product: AdminProduct) { const images = product.product_images ?? []; const { error } = await supabase.from('products').delete().eq('id', product.id); if (error) throw error; if (images.length) await supabase.storage.from('product-images').remove(images.map((image) => image.storage_path)) }
export async function uploadAdminProductImage(productId: string, productName: string, file: File) { const extension = file.name.split('.').pop()?.toLowerCase() || 'jpg'; const path = `products/${slugify(productName)}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from('product-images').upload(path, file, { upsert: false }); if (uploadError) throw uploadError; const { data: existing } = await supabase.from('product_images').select('storage_path').eq('product_id', productId).eq('position', 0).maybeSingle(); const { error: imageError } = await supabase.from('product_images').upsert({ product_id: productId, storage_path: path, alt_text: productName, position: 0 }, { onConflict: 'product_id,position' }); if (imageError) throw imageError; if (existing?.storage_path && existing.storage_path !== path) await supabase.storage.from('product-images').remove([existing.storage_path]); }
