import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { useAuth } from '../../features/auth/useAuth'
import { createReview, getProductReviews, type Review } from '../../services/reviewService'

function ProductReviews({ productId }: { productId: string }) {
  const { user } = useAuth(); const [reviews, setReviews] = useState<Review[] | null>(null); const [error, setError] = useState('')
  useEffect(() => { getProductReviews(productId).then(setReviews).catch(() => setReviews([])) }, [productId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); const { error: reviewError } = await createReview(productId, Number(form.get('rating')), String(form.get('title')), String(form.get('body'))); if (reviewError) return setError(reviewError.message); event.currentTarget.reset(); getProductReviews(productId).then(setReviews).catch(() => setReviews([])) }
  return <section className="mt-12 border-t border-blyver-ink/10 pt-8"><h2 className="font-serif text-2xl">Customer reviews</h2>{reviews === null ? <p className="mt-5 text-sm text-blyver-muted">Loading reviews…</p> : reviews.length ? <div className="mt-6 space-y-6">{reviews.map((review) => <article key={review.id} className="border-b border-blyver-ink/10 pb-6"><p className="text-blyver-champagne">{'★'.repeat(review.rating)}</p><h3 className="mt-2 font-medium">{review.title}</h3><p className="mt-2 text-sm leading-7 text-blyver-charcoal/70">{review.body}</p><p className="mt-3 text-xs text-blyver-muted">{review.profiles?.[0]?.full_name || 'Verified customer'}</p></article>)}</div> : <p className="mt-5 text-sm text-blyver-charcoal/65">No reviews yet.</p>}{user && <form onSubmit={submit} className="mt-10 border-t border-blyver-ink/10 pt-8"><p className="text-[11px] tracking-[0.18em] text-blyver-champagne">LEAVE A REVIEW</p><div className="mt-5 grid gap-4"><select required name="rating" defaultValue="5" className="w-fit border border-blyver-ink/20 bg-transparent px-3 py-2"><option value="5">5 — Excellent</option><option value="4">4 — Very good</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select><input required name="title" placeholder="Review title" className="border border-blyver-ink/20 bg-transparent px-4 py-3" /><textarea required name="body" rows={4} placeholder="Share your experience" className="border border-blyver-ink/20 bg-transparent px-4 py-3" /></div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<button className="mt-5 bg-blyver-ink px-5 py-3 text-[11px] tracking-[0.16em] text-blyver-ivory">SUBMIT REVIEW</button></form>}</section>
}
export default ProductReviews
